services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
      - ollama
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=graph2025
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
    networks:
      - app-network

  neo4j:
    image: neo4j:5
    container_name: neo4j-db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/graph2025
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - neo4jdata:/data
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "11434:11434"
    command: ["serve"]

volumes:
  neo4jdata:
  ollama_models:

networks:
  app-network: